build(dependencies): Fix kotlinx-serialization to fix JsonConvertException
The solved Exception is:
io.ktor.serialization.JsonConvertException: Illegal input: Receiver class ai.koog.prompt.executor.clients.google.GooglePart$Text$$serializer does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.KSerializer[] typeParametersSerializers()' of interface kotlinx.serialization.internal.GeneratedSerializer.